# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vc9QMBu3btmy_umCfdj073IxtuYtwnrN
"""

import json
import pandas as pd
from bs4 import BeautifulSoup
from urllib.request import urlopen

# url of the web page
scrape_url= "https://understat.com/league/EPL"

urlopen(scrape_url)

page_connect=urlopen(scrape_url)
page_connect

page_html=BeautifulSoup(page_connect,"html.parser")

page_html

page_html.findAll(name="script")[3].text[32:-3]

json_raw_str=page_html.findAll(name="script")[3].text

json_raw_str.index("')")

json_raw_str[32:296861]

json_data=json_raw_str[32:296861]

json_data=json_data.encode("utf8").decode("unicode_escape")

final_json_df=pd.json_normalize(json.loads(json_data))
final_json_df